default: &default
  adapter: postgresql
  encoding: utf-8
  database: postgres
  username: honor_admin
  password: pyXA3Y9@7D^co@#i6YBpo!%%Mw6rrSkvRSbWhLjcqJ
  host: honorary.postgres.database.azure.com
  sslmode: require
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default
